=== XavierJulien/MLBDA/tp5/dtd/restaurant.dtd
<!ELEMENT restaurant (nom,lieu,fermeture,etoile,menu)>
	<!ELEMENT nom (#PCDATA)>
	<!ELEMENT lieu (ville)>
		<!ELEMENT ville (nom,departement,plusBeauMonument)>
			<!ELEMENT departement (#PCDATA)>
			<!ELEMENT plusBeauMonument (nom,tarif)>
				<!ELEMENT tarif (#PCDATA)>
	<!ELEMENT fermeture (#PCDATA)>
	<!ELEMENT etoile (#PCDATA)>
	<!ELEMENT menu (nom,prix)>
		<!ELEMENT prix (#PCDATA)>

=== XavierJulien/MLBDA/tp5/dtd/restaurant.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE restaurant SYSTEM "restaurant.dtd">

<restaurant>
	<nom>universitaire</nom>
	<lieu>
		<ville>
			<nom>Paris</nom>
			<departement>75</departement>
			<plusBeauMonument>
				<nom>Louvre</nom>
				<tarif>8</tarif>
			</plusBeauMonument>
		</ville>
	</lieu>
	<fermeture>weekend</fermeture>
	<etoile>0</etoile>
	<menu>
		<nom>unique</nom>
		<prix>2</prix>
	</menu>
</restaurant>
